language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: jVlY17Ac/viz0RkvEnvJStyI9GDwXkcyBPAigaKcNuYnBln/sLXGdSqAtlsA7z1hHgqPFB4S53HSRuu1bwh/y6gb8gkEi/JDQwG4p2pdAZox5ETxbXGDtHi46XWGXtJKmxR4bfZ1RHnSLdKx1NZlt4gxdx02ZoiGyK6EZ3AS0ssI8D0hvf4Rc2kX+9wA5I9lRjRlwO2rwCc3S+pk2xEl1Io1aQZTbX2ByZCxnuBJwwqtiCzvABAB3qOlbIlu8CVQikdp7OBaKkLf1dTTEZky1cwt++GbcgxTZQv4nCl2xWmlRkaKQKuLuFUu0KeN1qMVlOv9hobzK4RUDe/c5UEGbZlebbsMtLMv9AD8+O7Cx9hwzr30IUlK69EkOOTjuP5n2SsGHUdBawZzQ05Ey6pc2iLlQ2+olsWnf7Qe4OVAPJzejyNzmtrKmkd6F0QLa57arH8F9FguX4ASdJsa7tx4q42lTE+3SSzYXiNlJboMVMordHD2FNF1j+6Ak4JIb3yP81p3Y3ImDgbm+mcIiaL8gtcoORILpcXh8XpNtnkD88E9Sfj3rweWDO4WDchk8oLZuHzBuyj6lg2L6A2Y2PSA+zVOg7hIJI5jh/ufnUuppXlu4W5i1wAtyL5L/j/frkqNZwsVbNIlKtDttdRCCYtXVuarD3Wmqgy0hvM2k92O2hY=
